"""empty message

Revision ID: b2ce4dbbd9b6
Revises: ee2dbe98b373
Create Date: 2019-08-31 14:30:05.607285

"""

# revision identifiers, used by Alembic.
revision = 'b2ce4dbbd9b6'
down_revision = 'ee2dbe98b373'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
