"""empty message

Revision ID: ee2dbe98b373
Revises: a3abe9ebdea6
Create Date: 2019-08-30 22:37:27.808487

"""

# revision identifiers, used by Alembic.
revision = 'ee2dbe98b373'
down_revision = 'a3abe9ebdea6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
